services:
  gitapi:
    container_name: gitapi
    build:
      context: github-backend
    ports:
      - '5000:5000'
    environment:
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - PORT=5000
      # - GITHUB_REDIRECT_URL=http://localhost:5000/login/github/callback
      - FRONTEND_REDIRECT_URL=http://localhost:3000

  gitapp:
    container_name: gitapp
    build:
      context: git-app
    ports:
      - '3000:80'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - gitapi
