###
GET http://localhost:5000/repos/public
Authorization: Bearer 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

###
GET http://localhost:5000/repos/organization
Authorization: Bearer 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

###
GET http://localhost:5000/ping


### Get github login
GET http://localhost:5000/login/github


### Get github accesstoken

GET http://localhost:5000/login/github/callback?code=7c133d9586b5eb9b090b